server:
  port: 8009
spring:
  application:
    name: cloud_consumer_hystrix_8009
eureka:
  instance:
    instance-id: ${spring.application.name}@${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://andy:andy@localhost:8002/eureka/