server:
  port: 8008
spring:
  application:
    name: cloud_consumer_feign_config_8008
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}@${server.port}
  client:
    service-url:
      defaultZone: http://andy:andy@localhost:8002/eureka
