server:
  port: 8005

spring:
  application:
    name: cloud_consumer_ribbon
eureka:
  client:
    service-url:
      defaultZone: http://andy:andy@localhost:8002/eureka
    enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}@${server.port}
