server:
  port: 8013
spring:
  application:
    name: cloud_turbine_complex
eureka:
  client:
    service-url:
      defaultZone: http://andy:andy@localhost:8002/eureka/
  instance:
    instance-id: ${spring.application.name}@${server.port}
    prefer-ip-address: true
turbine:
  appConfig: cloud_consumer_feign_fallback_9009,cloud_consumer_feign_hystrix_fallbackfactory_8010
  clusterNameExpression: "'default'"
