server:
  port: 8000

spring:
  application:
    name: cloud-provider
eureka:
  client:
    service-url:
      defaultZone: http://andy:andy@localhost:8002/eureka/

  instance:
    hostname: localhost
    instance-id: ${spring.application.name}@${server.port}
    prefer-ip-address: true