server:
  port: 8002
eureka:
  client:
    service-url:
      defaultZone: http://andy:andy@localhost:8002/eureka/
    fetch-registry: false
    register-with-eureka: false
spring:
  security:
    user:
      name: andy
      password: andy
