server:
  port: 7999
spring:
  application:
    name: cloud-provider-7999
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}@${server.port}
  client:
    service-url:
      defaultZone: http://andy:andy@localhost:8002/eureka/
