server:
  port: 8010
  servlet:
    context-path: /andy8010
spring:
  application:
    name: cloud_consumer_feign_hystrix_fallbackfactory_8010
eureka:
  client:
    service-url:
      defaultZone: http://andy:andy@localhost:8002/eureka/
  instance:
    instance-id: ${spring.application.name}@${server.port}
    # 增加了context-path 需要被turbine监控 作出此配置
    prefer-ip-address: true
    home-page-url-path: /andy8010
    metadata-map:
      cluster: CLOUD_CONSUMER_FEIGN_HYSTRIX_FALLBACKFACTORY_8010
      management:
        context-path: /andy8010/actuator
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream