server:
  port: 8006
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://andy:andy@register8002:8002/eureka/,http://andy:andy@register8003:8003/eureka/
spring:
  security:
    user:
      password: andy
      name: andy