server:
  port: 8001

spring:
  application:
    name: cloud_consumer
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}@${server.port}
    hostname: localhost
    status-page-url: /info
    health-check-url: /health
  client:
    service-url:
      defaultZone: http://andy:andy@localhost:8002/eureka/
